apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
  PGDATA: "/var/lib/postgresql/data/pgdata"
